### ISSUE TITLE
[EPIC] Go Chaos Worker

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe-chaos#121]
### Motivation

Currently we have [several shell scripts](https://github.com/zeebe-io/zeebe-chaos/tree/master/chaos-workers/chaos-experiments/scripts) to execute chaos experiments with [chaostoolkit](https://chaostoolkit.org/). The scripts are currently working well, but the maintenance is rather hard, especially for people which might not familiar enough with bash.

This is the reason why we already migrated some of them to a [kotlin based chaos worker](https://github.com/zeebe-io/zeebe-chaos/tree/master/chaos-workers/chaos-worker). But we haven't done this for scripts which directly interact with the kubernetes API. The problem here is that we would need an executable cli to reference them also in the chaostoolkit experiments, to run it locally. Furthermore, the interaction with kubernetes in go, I would say, is easier/better.

### Possible Solution

We create a new go cli, with [cobra](https://github.com/spf13/cobra). The cli allows to be executed by chaostoolkit locally. Furthermore, we use the zeebe go worker api such that we can register on the testbench. We use the go kubernetes client to interact with the kubernetes api, and use retry functionalities as we do in the shell scripts to make the experiments less flaky.

Benefit of this would be to familiarize a bit more with go and our provided go client.

### Alternative

We have to build a kotlin cli, which interacts with the kubernetes api. Here we could use a client like https://github.com/kubernetes-client/java or https://blog.marcnuri.com/kubernetes-client-java-fabric8-introduction

We reference in the chaostoolkit experiments the jar with dependencies.

#### Work

- [x] Setup go mod project
- [x] Setup corba
   - [x] setup first command -v/--version or -h/--help
   - [x] Build first image
- [x] Add [kubernetes go client](https://github.com/kubernetes/client-go)
  - [x] Add simple command to see all zeebe pods
- [x] Add zeebe go client dependency
  - [x] find out how to connect to the cluster
    - [x] either via exec http://runkiss.blogspot.com/2020/07/how-to-execute-command-on-kubernetes.html
    - [x] or via port forward might be better
  - [x] add topology command -> zeebe go client status
- [ ] Migrate first shell script
  - [ ] start with something simple like await readiness
- [x] Migrate one more complicated
  - [x] Kill leader for partition

**Comment by npepinpe** [comment]
I think Deepthi looked into using the fabric8 k8s client for her stuff, maybe she has some insights. Might be simer since you can integrate that with the kotlin stuff you already have? Just a thought

**Comment by deepthidevaki** [comment]
If you are interested in fabric8io, here is an example https://github.com/zeebe-io/zeebe-e2e-test/blob/3b78f522cd7be2925bf7a8fcea15d278b5b2330d/workers/src/main/java/io/camunda/zeebe/e2e/workers/PrepareTestHandler.java#L29-L31 
One advantage is that we can also test using kubernetes mock https://github.com/zeebe-io/zeebe-e2e-test/blob/3b78f522cd7be2925bf7a8fcea15d278b5b2330d/workers/src/test/java/io/camunda/zeebe/e2e/workers/PrepareTestHandlerTest.java#L11

**Comment by Zelldon** [comment]
Thanks @deepthidevaki :) :+1: I think this is also possible with the go k8 client :) https://medium.com/the-phi/mocking-the-kubernetes-client-in-go-for-unit-testing-ddae65c4302

**Comment by Zelldon** [comment]
supersed by https://github.com/zeebe-io/zeebe-chaos/issues/139
